# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bd343d3f85f69c389dfc98cf2c5285a28865d69c7e8c71bee18df006c1141ce8d749dc6435cb76170d9e1186adfa8ff117d5729905da28a771a487d2721dcde

test:
  secret_key_base: e8a70b4be0ca68a8786e2013d1ec823aa42c8eba37dad042d0d1340fa80b377d0f3024e49538477c95200d5632b8a00b08a456033176ab23d89cdacc89df8937

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
